---
title: "Untitled"
output: html_document
date: "2022-07-20"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
options(scipen = 999)

library(tidyverse)
library(knitr)
library(scales)
library(kableExtra)
library(readxl)
# source("R/eda.R")
```

## Intro

## Translate Variables

```{r}
file <- "data/_private/hh_survey/input/Reno HTS Dataset Final-08-02-2024.xlsx"
hh <- read_excel(file, sheet = 1)
per <- read_excel(file, sheet = 2)
loc <- read_excel(file, sheet = 4, col_types = c("33. Arrival Time" = "numeric"))

fix_colnames <- function(df){
  colnames <- colnames(df)
  colnames <- gsub("^\\d+[a-z]?\\.\\s", "", colnames)
  colnames <- gsub("\\s", "_", colnames)
  colnames(df) <- colnames
  return(df)
}

hh <- fix_colnames(hh) %>%
  rename(Sample_Number = HH_Sample_Number)
per <- fix_colnames(per)
loc <- fix_colnames(loc)
```


```{r}
translate_table <- function(df){
  equiv_tbl <- read_csv("data/hhs_equiv_table.csv")
  
  variables <- unique(equiv_tbl$VARIABLE)
  col_names <- colnames(df)
  for (variable in variables) {
    if (!(variable %in% col_names)) next
    
    tmp <- equiv_tbl %>%
      filter(VARIABLE == variable) %>%
      select(CODE, EQUIV)

    df <- df %>%
      mutate(!!paste0(variable, "_int") := !!sym(variable)) %>%
      rename(temp = variable) %>%
      left_join(tmp, by = c("temp" = "CODE")) %>%
      mutate(temp = ifelse(is.na(EQUIV), temp, EQUIV)) %>%
      select(-EQUIV) %>%
      rename(!!variable := temp) %>%
      relocate(!!paste0(variable, "_int"), .before = !!sym(variable))
  }
  return(df)
}
```

```{r}
translate_hh <- translate_table(hh) %>%
  mutate(across(where(is.character), ~ gsub("‘|’", "", .x)))
translate_per <- translate_table(per) %>%
  mutate(across(where(is.character), ~ gsub("‘|’", "", .x)))
translate_loc <- translate_table(loc) %>%
  mutate(across(where(is.character), ~ gsub("‘|’", "", .x)))
```

# Geocoding

```{r, include=FALSE}
hh_pts <- hh %>%
  mutate(unique_id = paste(HH_Longitude, HH_Latitude, sep = "_")) %>%
  select(
    unique_id,
    longitude = HH_Longitude,
    latitude = HH_Latitude
  )
per_pts <- bind_rows(
  per %>%
    mutate(unique_id = paste(Workplace_Longitude, Workplace_Latitude, sep = "_")) %>%
    select(unique_id, longitude = Workplace_Longitude, latitude = Workplace_Latitude),
  per %>%
    mutate(unique_id = paste(School_Longitude, School_Latitude, sep = "_")) %>%
    select(unique_id, longitude = School_Longitude, latitude = School_Latitude)
)
loc_pts <- loc %>%
  mutate(unique_id = paste(Location_Longitude, Location_Latitude, sep = "_")) %>%
  select(unique_id, longitude = Location_Longitude, latitude = Location_Latitude)

# Use this table in TransCAD to geocode points to TAZs
to_geocode <- bind_rows(hh_pts, per_pts, loc_pts) %>%
  group_by(unique_id) %>%
  slice(1) %>%
  filter(!is.na(longitude) & longitude != -1)
write_csv(to_geocode, "data/_private/hh_survey/output/to_geocode.csv")

# once geocoded externally, read it back in
geocoded_pts <- read_csv("data/_private/hh_survey/output/geocoded_points.csv") %>%
  select(unique_id, TAZ)

hh_with_tazs <- translate_hh %>%
  mutate(unique_id = paste(HH_Longitude, HH_Latitude, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(HomeTAZ = TAZ) %>%
  select(-unique_id)

per_with_taz <- translate_per %>%
  mutate(unique_id = paste(Workplace_Longitude, Workplace_Latitude, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(WorkTAZ = TAZ) %>%
  mutate(unique_id = paste(School_Longitude, School_Latitude, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(SchoolTAZ = TAZ) %>%
  select(-unique_id)

loc_with_taz <- translate_loc %>%
  mutate(unique_id = paste(Location_Longitude, Location_Latitude, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(LocationTAZ = TAZ) %>%
  select(-unique_id)
```

## Calculate HHStructure

```{r}
per_calc_ptypes <- per_with_taz %>%
  mutate(
    WAdult = ifelse(Employment == "Yes" & Age >= 18, 1, 0),
    NWAdult = ifelse(Employment == "No" & Age >= 18, 1, 0),
    Kid = ifelse(Age < 18, 1, 0),
    PreSch = ifelse(Age < 5, 1, 0),
    Senior = ifelse(Age >= 65, 1, 0),
    Licensed_Driver = ifelse(Licensed_Driver == "Yes", 1, 0)
  )

hhstructure <- per_calc_ptypes %>%
  group_by(Sample_Number) %>%
  summarise(
    WAdults = sum(WAdult), NWAdults = sum(NWAdult), HHKids = sum(Kid), 
    HHPreSchs = sum(PreSch), HHSeniors = sum(Senior),
    HHDrvLic = sum(Licensed_Driver)
  ) %>%
  mutate(HHStructure = paste0("HH_", WAdults, NWAdults, HHKids))

hh_add_strct <- hh_with_tazs %>%
  left_join(hhstructure, by = "Sample_Number")
  
```


## Convert modes to model modes

```{r}
convert_modes <- loc_with_taz %>%
  mutate(
    mode_model = case_when(
      Mode_of_Travel == "auto" & Number_of_People == 1 ~ "sov",
      Mode_of_Travel == "auto" & Number_of_People == 2 ~ "hov2",
      Mode_of_Travel == "auto" & Number_of_People >= 3 ~ "hov3",
      TRUE ~ Mode_of_Travel
    )
  )
```


## Identify tours

```{r}
id_tours <- convert_modes %>%
  arrange(Sample_Number, Person_Number, `Activity/Trip_Number`) %>%
  group_by(Sample_Number, Person_Number) %>%
  mutate(
    tour_start = case_when(
      Activity_Type_Code == "H" & `Activity/Trip_Number` == max(`Activity/Trip_Number`) ~ 0,
      `Activity/Trip_Number` == min(`Activity/Trip_Number`) ~ 1,
      Activity_Type_Code == "H" ~ 1,
      TRUE ~ 0
    ),
    tour_num = cumsum((tour_start))
  ) %>%
  # if a person only has one location listed for the day, they did not travel,
  # so assign them to "home" tour type.
  mutate(tour_type = ifelse(n() == 1, "home", NA)) %>%
  group_by(Sample_Number, Person_Number, tour_num) %>%
  mutate(
    tour_type = case_when(
      tour_type == "home" ~ "home",
      "W" %in% Activity_Type_Code ~ "work",
      # "U" %in% Activity_Type_Code ~ "univ",
      "SCH" %in% Activity_Type_Code ~ "school",
      any(grepl("PUDO Sch", Activity_Type_Code)) ~ "PUDO_Sch",
      any(grepl("PUDO Work", Activity_Type_Code)) ~ "PUDO_Work",
      any(grepl("PUDO Other", Activity_Type_Code)) ~ "PUDO_Other",
      # "Shp" %in% Activity_Type_Code ~ "shop",
      tour_num == 0 ~ "home",
      TRUE ~ "nm"
    ),
    # complete_tour = ifelse(last(Activity_Type_Code) == "H", 1, 0),
    tour_id = paste(Sample_Number, Person_Number, tour_num, sep = "_")
  )

# determine tour anchor place using the max duration, but break ties by
# purpose. For any remaining ties (same purpose and duration) just make the
# first one the anchor.
mark_anchor <- id_tours %>%
  mutate(
    Arrival_Time = hms::as_hms(Arrival_Time * 86400),
    Departure_Time = hms::as_hms(Departure_Time * 86400)
  ) %>%
  group_by(Sample_Number, Person_Number) %>%
  mutate(
    # activity_arr_mins = arr_hr * 60 + arr_min,
    # activity_dep_mins = dep_hr * 60 + dep_min,
    activity_arr_mins = lubridate::seconds(Arrival_Time) %>% as.integer() / 60,
    arr_hr = activity_arr_mins %/% 60 %>% as.integer(),
    arr_min = activity_arr_mins %% 60 %>% as.integer(),
    activity_dep_mins = lubridate::seconds(Departure_Time) %>% as.integer() / 60,
    # For people working 3rd shift, their last location is not home and does
    # not have a departure time. Give that a time of midnight for anchor calcs.
    activity_dep_mins = ifelse(
      Activity_Type_Code != "H" & `Activity/Trip_Number` == max(`Activity/Trip_Number`),
      24 * 60, activity_dep_mins
    ),
    dep_hr = activity_dep_mins %/% 60 %>% as.integer(),
    dep_min = activity_dep_mins %% 60 %>% as.integer(),
    activity_duration = ifelse(
      activity_arr_mins < activity_dep_mins,
      activity_dep_mins - activity_arr_mins,
      activity_dep_mins + 24 * 60 - activity_arr_mins
    ),
    activity_duration = ifelse(is.na(activity_duration), 0, activity_duration),
    activity_duration = as.integer(activity_duration),
    temp_dur = ifelse(Activity_Type_Code == "H", 0, activity_duration)
  ) %>%
  group_by(Sample_Number, Person_Number, tour_num) %>%
  mutate(
    anchor = ifelse(temp_dur == max(temp_dur), 100, 0),
    anchor = case_when(
      Activity_Type_Code == "W" ~ anchor + 3,
      Activity_Type_Code == "U" ~ anchor + 2,
      Activity_Type_Code == "Sch" ~ anchor + 1,
      TRUE ~ anchor,
    ),
    anchor = ifelse(anchor == max(anchor), 1, 0),
    check = cumsum(anchor),
    anchor = ifelse(check > 1, 0, anchor),
    anchor_taz = ifelse(anchor == 1, LocationTAZ, NA),
    anchor_duration = ifelse(anchor == 1, temp_dur, NA),
    # Calculate intermediate stops
    int_stop = ifelse(
      `Activity/Trip_Number` == min(`Activity/Trip_Number`) | 
        `Activity/Trip_Number` == max(`Activity/Trip_Number`) | anchor == 1,
      0, 1
    ),
    int_stop_fwd = ifelse(check == 0, int_stop, 0), # before anchor
    int_stop_ret = ifelse(check >= 1, int_stop, 0)  # after anchor
  ) %>%
  select(-temp_dur, -check)

# Identify primary and secondary modes. Primary is the highest-order mode on
# trip. The secondary mode is the second highest order.
id_tour_mode <- mark_anchor %>%
  mutate(
    primary_mode = case_when(
      "rail" %in% mode_model ~ "rail",
      "school_bus" %in% mode_model ~ "school_bus",
      "bus" %in% mode_model ~ "bus",
      "tnc" %in% mode_model ~ "tnc",
      "hov3" %in% mode_model ~ "hov3",
      "hov2" %in% mode_model ~ "hov2",
      "sov" %in% mode_model ~ "sov",
      "bike" %in% mode_model ~ "bike",
      "walk" %in% mode_model ~ "walk",
      "other" %in% mode_model ~ "other",
      TRUE ~ "other"
    ),
    temp = ifelse(mode_model == primary_mode, NA, mode_model),
    secondary_mode = case_when(
      "rail" %in% temp ~ "rail",
      "school_bus" %in% temp ~ "school_bus",
      "bus" %in% temp ~ "bus",
      # "hotel_shuttle" %in% temp ~ "hotel_shuttle",
      "tnc" %in% temp ~ "tnc",
      "hov3" %in% temp ~ "hov3",
      "hov2" %in% temp ~ "hov2",
      "sov" %in% temp ~ "sov",
      "bike" %in% temp ~ "bike",
      "walk" %in% temp ~ "walk",
      "other" %in% temp ~ "other",
      TRUE ~ primary_mode
    )
  ) %>%
  select(-temp)

tour_file <- id_tour_mode %>%
  group_by(tour_id) %>%
  summarize(
    Sample_Number = first(Sample_Number),
    Person_Number = first(Person_Number),
    tour_num = first(tour_num),
    tour_type = first(tour_type),
    # complete_tour = first(complete_tour),
    num_trips = n(),
    anchor_taz = max(anchor_taz, na.rm = TRUE),
    anchor_start_hr = sum(arr_hr[anchor == 1]),
    anchor_start_min = sum(arr_min[anchor == 1]),
    anchor_end_hr = sum(dep_hr[anchor == 1]),
    anchor_end_min = sum(dep_min[anchor == 1]),
    anchor_duration = max(anchor_duration, na.rm = TRUE),
    int_stop_fwd = sum(int_stop_fwd),
    int_stop_ret = sum(int_stop_ret),
    primary_mode = first(primary_mode),
    secondary_mode = first(secondary_mode),
    access_mode = first(na.omit(Transit_Access)),
    egress_mode = last(na.omit(Transit_Egress)),
    HH_Members_Max = max(HH_Members, na.rm = TRUE),
    HH_Members_Min = min(HH_Members, na.rm = TRUE),
    Non_HH_Members_Max = max(Non_HH_Members, na.rm = TRUE),
    Non_HH_Members_Min = min(Non_HH_Members, na.rm = TRUE)
  ) %>%
  mutate(
    anchor_taz = ifelse(anchor_taz == -Inf, NA, anchor_taz),
    # members max/min can be inf/-inf. This is mostly for home tours
    # (people who make no tours), but it also affects open tours at the start
    # of the day. Set them all to 1 person.
    across(HH_Members_Max:HH_Members_Min, ~ ifelse(is.finite(.x), .x, 1)),
    across(Non_HH_Members_Max:Non_HH_Members_Min, ~ ifelse(is.finite(.x), .x, 0))
  )
  # # tours with tour_num = 0 are where the person starts the day not at home.
  # filter(tour_num > 0 | tour_type == "home")
```

```{r}
stops_file <- id_tour_mode %>%
  ungroup() %>%
  filter(int_stop == 1) %>%
  mutate(stop_taz = LocationTAZ) %>%
  select(
    tour_id, int_stop_fwd, int_stop_ret, stop_taz, Activity_Type_Code,
    duration = activity_duration
  ) %>%
  # determine primary forward and return stop based on duration
  group_by(tour_id) %>%
  mutate(stop_id = row_number()) %>%
  ungroup() %>%
  arrange(tour_id, int_stop_fwd, desc(duration)) %>%
  group_by(tour_id, int_stop_fwd) %>%
  mutate(primary_stop = ifelse(row_number() == 1, 1, 0)) %>%
  ungroup() %>%
  arrange(tour_id, stop_id) %>%
  relocate(stop_id, .after = tour_id)
```


```{r}
# Update household file with numbers of workers who took a work tour that day
tours_by_hh <- tour_file %>%
  group_by(Sample_Number, Person_Number, tour_type) %>%
  summarize(count = n()) %>%
  pivot_wider(
    id_cols = c(Sample_Number, Person_Number), names_from = tour_type, 
    values_from = count, values_fill = 0
  ) %>%
  mutate(WorkersThatDay = ifelse(work > 0, 1, 0)) %>%
  group_by(Sample_Number) %>%
  summarize(across(work:WorkersThatDay, ~ sum(.x))) %>%
  rename_with(~ paste0(.x, "_tours"), work:nm)
  

hh_add_tours <- hh_add_strct %>%
  left_join(tours_by_hh, by = "Sample_Number") %>%
  relocate(WorkersThatDay, .after = WAdults) %>%
  mutate(
    BasicPattern = paste0(
      "P_",
      WorkersThatDay,
      Number_Persons - HHKids - WorkersThatDay, # adults not working that day,
      HHKids
    )
  )
```


## Create Trip File

```{r}
# first remove the mode xfer stops.
remove_xfers <- mark_anchor %>%
  filter(Activity_Type_Code != "X")

trip_file <- remove_xfers %>%
  # Remove the last place for each person. This also removes people who didn't
  # travel and so only have one place listed.
  # filter(`Activity/Trip_Number` != max(`Activity/Trip_Number`)) %>%
  group_by(Sample_Number, Person_Number) %>%
  arrange(Sample_Number, Person_Number, `Activity/Trip_Number`) %>%
  # group_by(tour_id) %>%
  transmute(
    tour_type = tour_type,
    trip_number = lead(`Activity/Trip_Number`),
    Weight_Factor = Weight_Factor,
    dep_hr = dep_hr,
    dep_min = dep_min,
    next_arr_hr = lead(arr_hr),
    next_arr_min = lead(arr_min),
    arr_hr = lead(arr_hr),
    arr_min = lead(arr_min),
    activity_duration = lead(activity_duration),
    mode = lead(mode_model),
    access_mode = lead(Transit_Access),
    egress_mode = lead(Transit_Egress),
    HH_Members = lead(HH_Members),
    Non_HH_Members = lead(Non_HH_Members),
    orig_purp = Activity_Type_Code,
    dest_purp = lead(Activity_Type_Code),
    o_taz = LocationTAZ,
    d_taz = lead(LocationTAZ),
    pa_format = ifelse(dest_purp == "H", 0, 1),
    p_taz = ifelse(pa_format == 1, o_taz, d_taz),
    a_taz = ifelse(pa_format == 1, d_taz, o_taz),
    p_purp = ifelse(pa_format == 1, orig_purp, dest_purp),
    a_purp = ifelse(pa_format == 1, dest_purp, orig_purp),
    purpose = case_when(
      p_purp == "H" ~ paste0("HB", a_purp),
      p_purp == "W" | a_purp == "W" ~ "NHBW",
      p_purp == "SHP" | a_purp == "SHP" ~ "NHBSHP",
      TRUE ~ "NHBO"
    ),
    purpose = ifelse(tour_type == "work", paste0("W_", purpose), paste0("N_", purpose)),
    purpose = ifelse(purpose %in% c("W_HBSHP", "W_HBSR", "W_HBU", "W_HBSCH", "W_NHBSHP"), "W_HBO", purpose),
    p_access_mode = ifelse(pa_format == 1, access_mode, egress_mode),
    p_egress_mode = ifelse(pa_format == 1, egress_mode, access_mode)
  ) %>%
  filter(!is.na(dep_hr) & !is.na(arr_hr)) %>%
  # ID external trips
  mutate(ix_type = case_when(
    is.na(o_taz) & is.na(d_taz) ~ "EE",
    !is.na(o_taz) & !is.na(d_taz) ~ "II",
    TRUE ~ "IX"
  ))

# Add TOD data
trip_add_tod <- trip_file %>%
  mutate(
    trip_dep_mins = dep_hr * 60 + dep_min,
    trip_arr_mins = arr_hr * 60 + arr_min,
    midpoint = (trip_arr_mins - trip_dep_mins) / 2 + trip_dep_mins,
    tod = case_when(
      trip_dep_mins < 420 ~ "NT",
      trip_dep_mins < 540 ~ "AM",
      trip_dep_mins < 900 ~ "MD",
      trip_dep_mins < 1080 ~ "PM",
      TRUE ~ "NT",
    )) %>%
  select(-trip_dep_mins, trip_arr_mins, midpoint)

# Add skim data
skim <- read_csv("data/input/skims/congested_skim.csv")
trip_add_skim <- trip_add_tod %>%
  left_join(skim, by = c("p_taz" = "From", "a_taz" = "To")) %>%
  mutate(skim_time = case_when(
    tod == "AM" ~ AM_900,
    tod == "MD" ~ MD_1300,
    tod == "PM" ~ PM_1730,
    tod == "NT" ~ NT_2200
  )) %>%
  select(-c(AM_900:NT_2200)) %>%
  # remove external trips
  filter(!is.na(p_taz) & !is.na(a_taz))
```

## Add tour summary to person file

```{r}
tours_by_per <- tour_file %>%
  group_by(Sample_Number, Person_Number, tour_type) %>%
  summarize(count = n()) %>%
  pivot_wider(
    id_cols = Sample_Number:Person_Number, names_from = tour_type, 
    values_from = count, values_fill = 0
  ) %>%
  rename_with(~ paste0(.x, "_tours"), work:nm)

per_add_tour_counts <- per_calc_ptypes %>%
  left_join(
    hh_with_tazs %>% select(-Weight_Factor), by = "Sample_Number"
  ) %>%
  left_join(tours_by_per, by = c("Sample_Number", "Person_Number")) %>%
  mutate(
    home_tours = ifelse(is.na(home_tours), 1, 0),
    nm_tours = ifelse(is.na(nm_tours), 0, nm_tours),
    work_tours = ifelse(is.na(work_tours), 0, work_tours),
    school_tours = ifelse(is.na(school_tours), 0, school_tours)
  )
```

```{r}
per_calc_iz <- per_add_tour_counts %>%
  mutate(
    IZ_Work = ifelse(HomeTAZ == WorkTAZ, 1, 0),
    IZ_School = ifelse(HomeTAZ == SchoolTAZ, 1, 0)
  )
```

```{r}
tour_remove_home <- tour_file %>%
  filter(tour_type != "home" & !is.na(anchor_start_hr))
```

## EDA for Non-Mandatory

```{r}
# # The EDA is going to regress on attraction end employment
# sedata <- read_csv("data/input/sedata/NewDemographics.csv")
# temp <- trip_add_skim %>%
#   left_join(sedata, by = c("trip_a_taz" = "TAZ")) %>%
#   filter(trip_purpose %in% c(
#     "HBO",
#     "HBSR",
#     "HBShp",
#     "NHBO",
#     "NHBShp",
#     "HBEO",
#     "HBG"
#   )) %>%
#   mutate(
#     tour_type = "all",
#     homebased = "all",
#     purp_scheme = trip_purpose,
#     # dur_scheme = case_when(
#     #   trip_purpose != "HBO" ~ "all",
#     #   activity_duration < 30 ~ "short",
#     #   TRUE ~ "long"
#     # )
#     dur_scheme = "all"
#   )
# temp_per <- per_calc_iz %>%
#   mutate(
#     is_worker = ifelse(Employment == "Yes", 1, 0),
#     is_senior = Senior,
#     is_kid = Kid
#   )
# 
# eda_df <- trip_eda(trip_df = temp)
# eda_df <- eda_df %>%
#   select(-tour_type, -homebased)
```

```{r}
per_fix_na <- per_calc_iz %>%
  mutate(Weight_Factor = ifelse(Weight_Factor == "NA", NA, Weight_Factor))
```



```{r, eval=FALSE}
write_csv(per_fix_na, "data/_private/hh_survey/output/output_persons.csv", na = "")
write_csv(hh_add_tours, "data/_private/hh_survey/output/output_households.csv", na = "")

write_csv(tour_remove_home, "data/_private/hh_survey/output/output_tours.csv", na = "")
write_csv(stops_file, "data/_private/hh_survey/output/output_stops.csv", na = "")
write_csv(trip_add_skim, "data/_private/hh_survey/output/output_trips.csv", na = "")
# write_csv(eda_df, "data/_private/hh_survey/output/eda.csv", na = "")
```

